// Distinct sub_category values from public.unique_products (deduplicated —
// the source list had two exact repeats: "Wedges" and "Trousers").
export const SUB_CATEGORIES: string[] = [
  "Ethnic Palazzo",
  "Coatigan",
  "Slip / Camisole",
  "Beanies",
  "Lehenga Set",
  "Loafers",
  "Leggings",
  "Bustier Top",
  "Gilets",
  "Saree",
  "Crop Top",
  "Jacket",
  "Capris",
  "Shirt / Shacket",
  "Corset",
  "Bralette / Bustier Top",
  "Sneakers",
  "Socks",
  "Shrug",
  "Top",
  "Skirt",
  "Activewear Bottoms",
  "Briefs / Panties",
  "Trousers",
  "Mules",
  "Sweatpants / Track Bottoms",
  "Palazzo Set",
  "Indo-Western",
  "Sliders",
  "Co-ord Set",
  "Anarkali Suit Set",
  "Platforms",
  "Hoodie",
  "Coat",
  "Poncho / Overcoat",
  "Dress",
  "Mini Dress",
  "Unstitched Suit Set",
  "Chinos",
  "Robes",
  "Waistcoat",
  "Kurta / Kurti",
  "Nightwear / Pyjama",
  "Formal Shoes",
  "Swimsuit",
  "Playsuit",
  "Corsets",
  "Fusion Set",
  "Flared / Bottoms",
  "Sharara Set",
  "Pullover",
  "Wedges",
  "Ethnic Blouse",
  "Activewear Top",
  "Sweatshirt",
  "Blazer",
  "Kolhapuris",
  "Boots",
  "Maxi Dress",
  "Punjabi Suit",
  "Cardigan",
  "Ballerinas",
  "Salwar Suit",
  "Gown Set",
  "T-Shirt",
  "Capes",
  "Bodysuit",
  "Mary Janes",
  "Garara Set",
  "Joggers",
  "Joggers & Sweatpants",
  "Jeggings",
  "Shapewear",
  "Flip-flops",
  "Straight Set",
  "Vest",
  "Activewear Sets",
  "Lingerie Set",
  "Sweater",
  "Jeans",
  "Sandals",
  "Chaniya Choli",
  "Sportswear / Activewear",
  "Clogs",
  "Tunic",
  "Flatforms",
  "Juttis",
  "Flats",
  "Kurta / Kurti Set",
  "Ethnic Gown",
  "Romper",
  "Jumpsuit",
  "Bra",
  "Dupatta",
  "A-Line Set",
  "Polo",
  "Loungewear Bottoms",
  "Juttis/Kolhapuris",
];
